// Baseline affinity of every catalog item over the fixed reference profiles (data/reference_profiles.json).
// Usage: build_baseline.mts [catalog.json] [out.json]. Output {itemId: {mean, sd, n}} plus the raw matrix. Cached.
import "./env.mts";
import { readFileSync, writeFileSync } from "node:fs";
(async () => {
  const { search } = await import("../lib/qloo/client.ts");
  const { mapCatalog, scoreCatalog } = await import("../lib/agent/score.ts");
  const { profiles } = JSON.parse(readFileSync("data/reference_profiles.json", "utf8"));
  const calls: any[] = [];
  const catPath = process.argv[2] ?? "data/catalog.json", outPath = process.argv[3] ?? "data/baseline.json";
  const items = JSON.parse(readFileSync(catPath, "utf8")).items;
  // ONLY_MISSING=1: score only items that have no vector yet and merge, instead of re-scoring the catalog.
  // ONLY_MISSING=1: keep the existing matrix and score only items that are not in it yet.
  const prevMatrix: Record<string, Record<string, number>> = process.env.ONLY_MISSING ? JSON.parse(readFileSync(outPath, "utf8")).matrix : {};
  const known = new Set(Object.values(prevMatrix).flatMap((m) => Object.keys(m)));
  const todo = items.filter((i: any) => !known.has(i.id));
  const itemIds = await mapCatalog(calls, todo);
  const matrix: Record<string, Record<string, number>> = { ...prevMatrix };
  for (const p of profiles) {
    const hit = (await search(p.name, p.type, calls)).results?.[0];
    if (!hit) { console.log("profile not found:", p.name); continue; }
    const { scores } = await scoreCatalog([hit.entity_id], itemIds, calls, todo);
    const key = `${p.name} -> ${hit.name}`;
    matrix[key] = { ...(matrix[key] ?? {}), ...Object.fromEntries([...scores].map(([id, s]) => [id, s.affinity])) };
    console.log(`${p.name} -> ${hit.name}: ${scores.size} items scored`);
  }
  const baseline: Record<string, { mean: number; sd: number; n: number }> = {};
  const ids = new Set(Object.values(matrix).flatMap((m) => Object.keys(m)));
  for (const id of ids) {
    const v = Object.values(matrix).map((m) => m[id]).filter((x) => typeof x === "number");
    const mean = v.reduce((a, b) => a + b, 0) / v.length;
    const sd = Math.sqrt(v.reduce((a, b) => a + (b - mean) ** 2, 0) / v.length);
    baseline[id] = { mean: +mean.toFixed(4), sd: +sd.toFixed(4), n: v.length };
  }
  writeFileSync(outPath, JSON.stringify({ note: "Generated by scripts/build_baseline.mts", baseline, matrix }, null, 1) + "\n");
  console.log("items with baseline:", Object.keys(baseline).length, "| live Qloo calls:", calls.filter((c) => c.cache === "miss").length);
})();
